### ISSUE TITLE
UnicodeEncodeError po startu

### ISSUE THREAD

**Issue by landam** [ctu-geoforall-lab/qgis-vfk-plugin-old#32]
Po startu se objevi nasledujici chyba:

```
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 56: ordinal not in range(128)

Traceback (most recent call last):
  File "C:/Users/koubav/.qgis2/python/plugins\qgis-vfk-plugin-release-2_0\mainApp.py", line 255, in runLoadingLayer
    if not self.loadVfkFile(fileName, errorMsg):
  File "C:/Users/koubav/.qgis2/python/plugins\qgis-vfk-plugin-release-2_0\mainApp.py", line 402, in loadVfkFile
    "Open OGR datasource (using DB: {})".format(self.__mDataSourceName))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 56: ordinal not in range(128)
```

**Comment by landam** [comment]
Oprava 4c93754 pod Windows evidentne zpusobuje qDebug(): unexpected type unicode
